[workspace]
members = [
  # Libraries
  "parser",
  "eval",
  "typing",
  # CLI app
  "cli",
  # E2E tests
  "e2e-tests/wasm",
  "e2e-tests/no-std",
]
resolver = "2"

# Speed up big integer crates.
[profile.dev.package.num-bigint]
opt-level = 2
[profile.dev.package.glass_pumpkin]
opt-level = 2
