[workspace]
members = ["parser", "eval", "test-wasm", "typing"]
exclude = ["cli", "test-nostd"]

# Speed up big integer crates.
[profile.dev.package.num-bigint]
opt-level = 2
[profile.dev.package.glass_pumpkin]
opt-level = 2
