[package]
name = "arithmetic-parser"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
description = "Parser for arithmetic expressions with flexible literals and support of type annotations."
repository = "https://github.com/slowli/arithmetic-parser"

[dependencies]
# Public dependencies (present in the public API).
anyhow = "1.0.27"
nom = "5.1.1"
nom_locate = "1.0.0"

[dev-dependencies]
assert_matches = "1.3.0"
hex = "0.4.2"
num-complex = "0.2.4"
