[workspace]
members = ["parser", "eval", "cli", "test-wasm", "typing"]

# Speed up big integer crates.
[profile.dev.package.num-bigint]
opt-level = 2
[profile.dev.package.glass_pumpkin]
opt-level = 2
