# `cargo-deny` configuration.

feature-depth = 1

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
notice = "warn"
severity-threshold = "Medium"

[licenses]
unlicensed = "deny"
allow = [
  # Permissive open-source licenses
  "MIT",
  "Apache-2.0",
  "BSL-1.0",
  "Unicode-DFS-2016",
]
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
skip = [
  # `bitflags` v1 is still used by many crates. Since it's largely a macro,
  # having multiple versions seems OK.
  { name = "bitflags", version = "^1" },
]
skip-tree = [
  # `cortex-m` crates (which are only used in the no-std test crate) have some outdated deps.
  { name = "cortex-m", version = "^0.7" },
  { name = "cortex-m-rt", version = "^0.7" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = [
  # Temporarily allow to depend on a revision that has `atty` dep removed
  "https://github.com/slowli/term-transcript.git",
]
