# `cargo-deny` configuration.

[output]
feature-depth = 1

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"

[licenses]
allow = [
  # Permissive open-source licenses
  "MIT",
  "Apache-2.0",
  "BSL-1.0",
  "Unicode-DFS-2016",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "deny"
allow-wildcard-paths = true
skip-tree = [
  # `cortex-m` crates (which are only used in the no-std test crate) have some outdated deps.
  { name = "cortex-m", version = "^0.7" },
  { name = "cortex-m-rt", version = "^0.7" },
  # Used by some less frequently updated crates; since it only provides WinAPI declarations,
  # multiple versions should be OK (?).
  { name = "windows-sys", version = "^0.52" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
