[package]
name = "arithmetic-typing"
version = "0.3.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "Hindley-Milner type inference for arithmetic expressions."
repository = "https://github.com/slowli/arithmetic-parser"
categories = ["mathematics"]
keywords = ["typing", "type-system", "arithmetic", "scripting", "language"]

[dependencies]
arithmetic-parser = { version = "0.3.0", path = "../parser" }

anyhow = "1.0.27"
nom = { version = "7", default_features = false, features = ["alloc"] }
num-traits = "0.2.14"

[dev-dependencies]
assert_matches = "1.5.0"
hex = "0.4.3"
pulldown-cmark = "0.8.0"
version-sync = "0.9"
