[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"

[build]
target = "thumbv7m-none-eabi"

[profile.release]
opt-level = "z" # Optimize for size, rather than speed
lto = true
codegen-units = 1
