[package]
name = "arithmetic-parser-cli"
version = "0.3.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "CLI / REPL for arithmetic expressions."
repository = "https://github.com/slowli/arithmetic-parser"

[dependencies]
anyhow = "1.0.27"
atty = "0.2.14"
codespan = "0.11.1"
codespan-reporting = "0.11.1"
num-complex = "0.4.0"
num-traits = "0.2.14"
rustyline = "9.0.0"
structopt = "0.3.13"
textwrap = "0.11.0"
unindent = "0.1.6"

[[bin]]
name = "arithmetic-parser"
path = "src/main.rs"

[dependencies.arithmetic-parser]
version = "0.3.0"
path = "../parser"

[dependencies.arithmetic-eval]
version = "0.3.0"
path = "../eval"
features = ["complex"]

[dependencies.arithmetic-typing]
version = "0.3.0"
path = "../typing"

# TODO: use published version
[dev-dependencies.term-transcript]
version = "0.1.0"
git = "https://github.com/slowli/term-transcript.git"
rev = "685eabc356cd86a826d1bdf11bbcf7548f170c62"

[workspace]
# Separate workspace since we need a lockfile
