[package]
name = "arithmetic-parser-cli"
version = "0.2.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
description = "CLI / REPL for arithmetic expressions."
repository = "https://github.com/slowli/arithmetic-parser"

[dependencies]
anyhow = "1.0.27"
codespan = "0.9.0"
codespan-reporting = "0.9.0"
num-complex = "0.4.0"
num-traits = "0.2.14"
rustyline = "7.0.0"
structopt = "0.3.13"
unindent = "0.1.6"

[dependencies.arithmetic-parser]
version = "0.2.0"
path = "../parser"

[dependencies.arithmetic-eval]
version = "0.2.0"
path = "../eval"
features = ["complex"]

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"
