[package]
name = "arithmetic-parser-cli"
version = "0.2.0-beta.1"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
description = "CLI / REPL for arithmetic expressions."
repository = "https://github.com/slowli/arithmetic-parser"

[dependencies]
anyhow = "1.0.27"
codespan = "0.9.0"
codespan-reporting = "0.9.0"
num-complex = "0.3.0"
rustyline = "6.0.0"
structopt = "0.3.13"
typed-arena = "2.0.1"
unindent = "0.1.6"

[dependencies.arithmetic-parser]
version = "0.2.0-beta.1"
path = "../parser"
features = ["num-complex"]

[dependencies.arithmetic-eval]
version = "0.2.0-beta.1"
path = "../eval"

[dev-dependencies]
assert_cmd = "1.0.1"
predicates = "1.0.5"

