[package]
name = "arithmetic-parser-cli"
version = "0.3.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "CLI / REPL for arithmetic expressions."
repository = "https://github.com/slowli/arithmetic-parser"

[[bin]]
name = "arithmetic-parser"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.27"
atty = "0.2.14"
clap = { version = "4.0.32", features = ["derive", "env", "wrap_help"] }
codespan = "0.11.1"
codespan-reporting = "0.11.1"
num-complex = "0.4.0"
num-traits = "0.2.14"
rustyline = "12.0.0"
textwrap = "0.16.0"
unindent = "0.2.3"

arithmetic-parser = { version = "0.3.0", path = "../parser" }
arithmetic-eval = { version = "0.3.0", path = "../eval", features = ["complex"] }
arithmetic-typing = { version = "0.3.0", path = "../typing" }

[dev-dependencies]
term-transcript = "0.3.0"
