[package]
name = "arithmetic-parser"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
description = "Parser for arithmetic expressions with flexible literals and type annotations."
repository = "https://github.com/slowli/arithmetic-parser"
categories = ["parser-implementations", "mathematics", "no-std"]
keywords = ["parser", "arithmetic"]

[dependencies]
# Public dependencies (present in the public API).
anyhow = "1.0.27"
nom = "5.1.1"
nom_locate = "2.0.0"
num-traits = "0.2.11"

# Optional dependencies (public)
num-complex = { version = "0.2.4", optional = true }

[dev-dependencies]
assert_matches = "1.3.0"
hex = "0.4.2"

[[example]]
name = "complex_c"
path = "examples/complex_c.rs"
required-features = ["num-complex"]
