name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Minimum supported Rust version.
  msrv: 1.46.0
  # Minimum supported Rust version for CLI.
  msrv_cli: 1.52.0
  # Nightly Rust toolchain for building docs and checking nostd support.
  nightly: nightly-2021-12-03

jobs:
  # Checks minimum supported Rust version.
  build-msrv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-msrv-cargo-build-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.msrv }}
          override: true

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --all-targets
      - name: Run doc tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --doc

      - name: Run parser example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p arithmetic-parser --all-features --example complex_c
      - name: Run eval example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p arithmetic-eval --example owned_module
      - name: Run ElGamal encryption example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path eval/Cargo.toml --example el_gamal --features bigint,num-bigint/rand
      - name: Run cyclic group example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path eval/Cargo.toml --example cyclic_group --features bigint,num-bigint/rand
      - name: Run typing example (strings)
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p arithmetic-typing --example strings
      - name: Run typing example (num_or_bytes)
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p arithmetic-typing --example num_or_bytes

  build-msrv-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: |
            target/
            cli/target/
          key: ${{ runner.os }}-msrv-cli-cargo-build-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.msrv_cli }}
          override: true

      - name: Build CLI
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path=cli/Cargo.toml --all-features --all-targets

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: |
            target/
            cli/target/
          key: ${{ runner.os }}-cargo-build-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-features --all-targets -- -D warnings
      - name: Clippy CLI
        uses: actions-rs/clippy-check@v1
        with:
          name: "clippy (CLI)"
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --manifest-path=cli/Cargo.toml --all-features --all-targets -- -D warnings

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --all-targets
      - name: Run CLI tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=cli/Cargo.toml --all-features --all-targets
      - name: Run doc tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features --doc

      - name: Run parser example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p arithmetic-parser --all-features --example complex_c
      - name: Run eval example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p arithmetic-eval --example owned_module
      - name: Run ElGamal encryption example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path eval/Cargo.toml --example el_gamal --features bigint,num-bigint/rand
      - name: Run cyclic group example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path eval/Cargo.toml --example cyclic_group --features bigint,num-bigint/rand
      - name: Run typing example (strings)
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p arithmetic-typing --example strings
      - name: Run typing example (num_or_bytes)
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p arithmetic-typing --example num_or_bytes

      - name: Compile WASM
        run: (cd e2e-tests/wasm; wasm-pack build --target nodejs)
      - name: Run WASM
        run: node e2e-tests/wasm/test.js

  # Checks that the crate actually builds without `std`. To do this,
  # we take a target (`thumbv7m-none-eabi`) that does not have `std` support.
  build-nostd:
    needs:
      - build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e-tests/no-std

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-nostd-cargo-build-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          override: true
          components: rustfmt, clippy
          target: thumbv7m-none-eabi

      # Since it's impossible to include the `nostd` crate into the common workspace,
      # we need to perform fmt / clippy checks for it separately.
      - name: Format
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --bin arithmetic-parser-nostd --all-features -- -D warnings

      - name: Run binary
        run: cargo run --release

  document:
    if: github.event_name == 'push'
    needs:
      - build
      - build-msrv
      - build-msrv-cli
      - build-nostd
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-cargo-document-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.nightly }}
          profile: minimal
          override: true

      - name: Build docs
        run: |
          cargo clean --doc && \
          cargo rustdoc -p arithmetic-parser --all-features -- -Z unstable-options \
            --extern-html-root-url anyhow=https://docs.rs/anyhow/~1.0.27 \
            --extern-html-root-url nom=https://docs.rs/nom/~7.0.0 \
            --extern-html-root-url nom_locate=https://docs.rs/nom_locate/~4.0.0 && \
          cargo rustdoc -p arithmetic-eval --all-features -- --cfg docsrs
          cargo rustdoc -p arithmetic-typing --all-features -- --cfg docsrs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: target/doc
          SINGLE_COMMIT: true
